name: AntOps change risk

on:
  pull_request:

jobs:
  assess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Artificial-Works/antops-developer/actions/change-risk@v0.2.1
        with:
          api-key: ${{ secrets.ANTOPS_API_KEY }}
          files: |
            Dockerfile
            compose.yaml
            main.tf
            openapi.yaml
